Update notes

diff --git a/FCC-SQL-JS-Node-RelationalDatabases-Certificate/1.4-Learn-Bash-Scripting-Building-5-Programs/notes b/FCC-SQL-JS-Node-RelationalDatabases-Certificate/1.4-Learn-Bash-Scripting-Building-5-Programs/notes
--- a/FCC-SQL-JS-Node-RelationalDatabases-Certificate/1.4-Learn-Bash-Scripting-Building-5-Programs/notes
+++ b/FCC-SQL-JS-Node-RelationalDatabases-Certificate/1.4-Learn-Bash-Scripting-Building-5-Programs/notes
@@ -28,7 +28,8 @@ eStart : 19March2025
     STATEMENTS
   fi
 Your program is expecting an integer to count down from as its argument. You can compare integers inside the brackets ([[ ... ]]) of your if with 
--eq (equal), -ne (not equal), -lt (less than), -le (less than or equal), -gt (greater than), -ge (greater than or equal).
+  -eq (equal), -ne (not equal), -lt (less than), -le (less than or equal), -gt (greater than), -ge (greater than or equal).
+  !, &&, and || to compare multiple expressions. There's also == and != operators for an individual expression.
 Change your if condition to check if your first argument is less than 5.
   if [[ $1 -lt 5 ]]
   then
@@ -36,11 +37,33 @@ Change your if condition to check if your first argument is less than 5.
   else
     echo false
   fi
-
-
-
-
-
+'echo $?'  #Nothing happened? Each command has an exit status that can be accessed with '$?'. View the exit status of the last command with 'echo $?' exit status '0' = 'true'
+';' #you can string statements together into oneliners using ';' '[[ 4 -ge 5 ]]; echo $?' will run '4 > 5' and return the exit code with '$?'
+exit code: 127 #command not found, with an exit status of 127. Anything but 0 means there was an error with the command.
+exit code: 2 #invalid option/flag
+exit code: 1 #command failed
+[[ -x countdown.sh ]]; echo $? #check if you have execute permissions for countdown.sh, returns exit code '0' for yes
+if statement with 'then' keyword for a countdown 'gt' = greater than '$1' = first argument :
+  if [[ $1 -gt 0 ]]
+  then
+    for (( i = $1; i > 0; i-- ))
+    do
+      echo $i
+    done
+  else
+    echo Include a positive integer as the first argument.
+  fi
+'/bin' is binaries folder, and contains commands you can run
+'sleep 3' causes the shell/script to stop for 3 seconds before running again
+: ' this is a multiline comment in bash ' 
+While loop syntax :
+  I=$1
+  while [[ $I -ge 0 ]]
+  do
+    echo $I
+    (( I-- ))
+    sleep 1
+  done
 
 
 
