Update Notes

diff --git a/FCC-SQL-JS-Node-RelationalDatabases-Certificate/Notes b/FCC-SQL-JS-Node-RelationalDatabases-Certificate/Notes
--- a/FCC-SQL-JS-Node-RelationalDatabases-Certificate/Notes
+++ b/FCC-SQL-JS-Node-RelationalDatabases-Certificate/Notes
@@ -279,7 +279,101 @@ Each primary key column should follow the naming convention table_name_id. For e
 Each foreign key column should have the same name as the column it is referencing
 '\q' to quit PostgreSQL terminal then type 'pg_dump -cC --inserts -U freecodecamp universe > universe.sql' to save the commands for tutorial
 
-
+19March2025 - Learn Bash Scripting by Building Five Programs =============================================================================================================================
+https://www.freecodecamp.org/learn/relational-database/learn-bash-scripting-by-building-five-programs/build-five-programs
+'sh questionnaire.sh' # you need a prefix with 'sh' similar to './' to run a shell script 'sh' stands for shell
+'bash questionnaire.sh' # to run it in 'bash' born again shell
+'which bash' # '/usr/bin/bash' where bash lives, 'which' shows where a program is 
+'#!<path_to_interpreter>' # shebang shebang oh baby she move she move I go crazy, she rook like a butterfly but sting like a bee -
+'#!/bin/bash' #tell the computer to run from this path -  tell your computer which interpreter to use - add it to the top of your script
+'./questionnaire.sh' #this is what I've been using for years to run my shell scripts
+'ls -l <file name>' #will list all privileges for the file 
+-rw-r--r--. All but the first character (-) describe permissions different users have with the file. r means read, w means write, x means execute
+'chmod +x questionnaire.sh' # in the terminal to give everyone executable permissions.
+'VARIABLE_NAME=VALUE' #Bash has variables, functions, and other things you might be familiar with. You can create a variable with VARIABLE_NAME=VALUE. 
+  There cannot be any spaces around the equal (=) sign. If a variable has any spaces in it, place double quotes around it. 
+'$VARIABLE_NAME' #To use a variable, place '$' in front of it like this: 
+'read VARIABLE_NAME' #you want to be able to accept input from a user. You can do that with 'read' like this: 
+'echo Hello $NAME.' #to print the name, notice how theres no quote marks or escape characters, I guess you can do it raw in bash
+'man echo' #use 'manual' pages to get info about the command 'echo' since 'echo --help' doesn't work
+'echo -e "\n~~ Questionnaire ~~\n"' # '-e' flag enables escape characters like '\n' escape character for new line
+'touch countdown.sh' #create a new file with touch
+'echo $*' #will print whatever the arguments are when running the script for example './countdown.sh arg1 arg2 arg3' will print 'arg1 arg2 arg3'
+'echo $1' #will print out the first argument given(there is no variable named '1')
+'help' #type JUST 'help' in the bash shell and it will show you ALL available commands
+'if' statements syntax (notice the fi at the end? fwhy?) :
+  if [[ CONDITION ]]
+  then
+    STATEMENTS
+  else
+    STATEMENTS
+  fi
+Your program is expecting an integer to count down from as its argument. You can compare integers inside the brackets ([[ ... ]]) of your if with 
+  -eq (equal), -ne (not equal), -lt (less than), -le (less than or equal), -gt (greater than), -ge (greater than or equal).
+  !, &&, and || to compare multiple expressions. There's also == and != operators for an individual expression.
+Change your if condition to check if your first argument is less than 5.
+  if [[ $1 -lt 5 ]]
+  then
+    echo true
+  else
+    echo false
+  fi
+'echo $?'  #Nothing happened? Each command has an exit status that can be accessed with '$?'. View the exit status of the last command with 'echo $?' exit status '0' = 'true'
+';' #you can string statements together into oneliners using ';' '[[ 4 -ge 5 ]]; echo $?' will run '4 > 5' and return the exit code with '$?'
+exit code: 127 #command not found, with an exit status of 127. Anything but 0 means there was an error with the command.
+exit code: 2 #invalid option/flag
+exit code: 1 #command failed
+[[ -x countdown.sh ]]; echo $? #check if you have execute permissions for countdown.sh, returns exit code '0' for yes
+if statement with 'then' keyword for a countdown 'gt' = greater than '$1' = first argument :
+  if [[ $1 -gt 0 ]]
+  then
+    for (( i = $1; i > 0; i-- ))
+    do
+      echo $i
+    done
+  else
+    echo Include a positive integer as the first argument.
+  fi
+'/bin' is binaries folder, and contains commands you can run
+'sleep 3' causes the shell/script to stop for 3 seconds before running again
+: ' this is a multiline comment in bash ' 
+While loop syntax :
+  I=$1
+  while [[ $I -ge 0 ]]
+  do
+    echo $I
+    (( I-- ))
+    sleep 1
+  done
+'printenv' #print environment
+'echo $LANG' #prints environment language variable
+'echo $RANDOM' #prints a random number - The RANDOM variable will generate a random number between 0 and 32767 - 
+  You can use the modulus operator to make it in the range you want. In your script, change the NUMBER variable to '$RANDOM%75'
+echo $(( J * 5 + 25 )) #how to run a mathematical equation on the variable J, and print out the answer
+'declare' #new keyword to declare a variable 'declare -p J' will declare the variable J
+'echo $(( RANDOM % 75 + 1 ))' #will run random command and give a result from 1-75
+Else If Statements Syntax :
+  if (( CONDITION ))
+  then
+    STATEMENTS
+  elif [[ CONDITION ]]
+  then
+    STATEMENTS
+  fi
+ARR=("a" "b" "c") #syntax for creating an array
+echo ${ARR[1]} #how to access that array and print value [1], index is 0 based, so that would be "b", notice it's '{' curly braces not '(' parenthesis
+echo ${ARR[*]} #to print every item in the array, 'echo ${ARR[@]}' also works
+Function Syntax : 
+  FUNCTION_NAME() {
+    STATEMENTS
+  }
+Until Loop Syntax (until loop is very similar to the while loop you used. It will execute the loop until a condition is met.) :
+  until [[ CONDITION ]]
+  do
+    STATEMENTS
+  done
+'[[ hello =~ el ]]; echo $?' # '=~' equals tilda returns true if there is a partial match, allows pattern matching - this will return '0' for 'true' 
+'[[ "hello world" =~ ^h ]]; echo $?' #regex, check if "hello world" starts with h
 
 
 
